pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

recipe_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('recipes/', include('recipes.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:recipe_id>', views.recipe, name='recipe'),
    path('', views.index, name='recipes'),
    path('search', views.search, name='search'),
    path('add_to_favourites', views.add_to_favourites, name='add_to_favourites'),
    path('remove_from_favourites', views.remove_from_favourites, name='remove_from_favourites'),
    path('create_recipe', views.create_recipe, name='create_recipe'),
    path('edit/<int:recipe_id>', views.edit_recipe, name='edit_recipe'),
]

recipes/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django_utils.choices import Choice, Choices
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating


class Recipe(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, )
    users_who_like = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='favourites')
    title = models.CharField(max_length=200)
    ingredients = models.TextField()
    description = models.TextField()
    preparation_time_in_minutes = models.IntegerField()
    serves = models.IntegerField(blank=True)

    class CategoryChoices(Choices):
        dinner = Choice(1, 'Obiady')
        breakfast = Choice(2, 'Śniadania')
        supper = Choice(3, 'Kolacje')
        snack = Choice(4, 'Przekąski')
        dessert = Choice(5, 'Desery')
        other = Choice(6, 'Inne')

    category = models.PositiveIntegerField(choices=CategoryChoices.choices, default=CategoryChoices.dinner)

    class DifficultyChoices(Choices):
        easy = Choice(1, 'Łatwe')
        medium = Choice(2, 'Średnie')
        hard = Choice(3, 'Trudne')

    difficulty = models.PositiveIntegerField(choices=DifficultyChoices, default=DifficultyChoices.easy)

    class DietChoices(Choices):
        vegan = Choice(1, 'Wegańska')
        vegetarian = Choice(2, 'Wegetariańska')
        meat = Choice(3, 'Bez ograniczeń')

    diet = models.PositiveIntegerField(choices=DietChoices, default=DietChoices.meat)
    ratings = GenericRelation(Rating, related_query_name='recipes_rating')
    is_published = models.BooleanField(default=True)
    is_recipe_of_month = models.BooleanField(default=False)
    added_date = models.DateTimeField(default=timezone.now)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.title

recipes/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Recipe


class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'preparation_time_in_minutes', 'serves', 'difficulty', 'category', 'diet', 'ingredients',
                  'description', 'photo_main', 'photo_1', 'photo_2', 'photo_3']
        labels = {
            'title': 'Tytuł',
            'preparation_time_in_minutes': 'Czas przygotowania w minutach',
            'serves': 'Ilość porcji',
            'difficulty': 'Stopień trudności',
            'category': 'Kategoria',
            'diet': 'Dieta',
            'ingredients': 'Składniki',
            'description': 'Opis przygotowania',
            'photo_main': 'Zdjęcie główne',
            'photo_1': 'Zdjęcie 2',
            'photo_2': 'Zdjęcie 3',
            'photo_3': 'Zdjęcie 4',
        }

    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

recipes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import messages
from django.http import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Recipe
from django.contrib.auth.models import User

from .forms import RecipeForm


def index(request):
    recipes = Recipe.objects.order_by('-added_date').filter(is_published=True)
    paginator = Paginator(recipes, 6)
    page = request.GET.get('page')
    page_recipes = paginator.get_page(page)

    context = {'recipes': page_recipes}

    return render(request, 'recipes/recipes.html', context)


def recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    is_favourite = False

    if request.user.is_authenticated:
        user = get_object_or_404(User, pk=request.user.id)
        if user in recipe.users_who_like.all():
            is_favourite = True

    context = {'recipe': recipe, 'is_favourite': is_favourite}
    return render(request, 'recipes/recipe.html', context)


def add_to_favourites(request):
    if request.method == "POST":
        try:
            recipe_id = request.POST.get('recipe_id')
            recipe = get_object_or_404(Recipe, pk=recipe_id)
            user = get_object_or_404(User, pk=request.user.id)
            if not user in recipe.users_who_like.all():
                recipe.users_who_like.add(user)
            return JsonResponse({"status": "success"}, status=200)

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)


def remove_from_favourites(request):
    if request.method == "POST":
        try:
            recipe_id = request.POST.get('recipe_id')
            recipe = get_object_or_404(Recipe, pk=recipe_id)
            user = get_object_or_404(User, pk=request.user.id)
            if user in recipe.users_who_like.all():
                recipe.users_who_like.remove(user)
                print('usunięto')
            return JsonResponse({"status": "success"}, status=200)

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)


def create_recipe(request):
    if request.user.is_anonymous:
        messages.info(request, 'Żeby dodwać przepisy musisz być zalogowany')
        return redirect('index')
    else:
        if request.method == 'POST':
            author = request.user
            new_recipe = Recipe(author=request.user)
            form = RecipeForm(request.POST, request.FILES, instance=new_recipe)

            if form.is_valid():
                new_recipe.save()
                return redirect('recipes')
        else:
            form = RecipeForm()

        context = {'form': form}
        return render(request, 'recipes/create_recipe.html', context)


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.user != recipe.author:
        messages.info(request, 'Tylko autor przepisu może go modyfikować')
        return redirect('recipes')
    else:
        if request.method == 'POST':
            form = RecipeForm(request.POST, request.FILES, instance=recipe)
            if form.is_valid():
                recipe.save()
                return redirect('recipe', recipe_id=recipe_id)
        else:
            form = RecipeForm(instance=recipe)

        context = {'form': form,
                   'recipe_id': recipe_id}
        return render(request, 'recipes/edit_recipe.html', context)


def search(request):
    queryset_list = Recipe.objects.order_by('-added_date')

    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(Q(description__icontains=keywords) | Q(title__icontains=keywords))

    if 'category' in request.GET:
        category = request.GET['category']
        if category:
            queryset_list = queryset_list.filter(category=category)

    if 'diet' in request.GET:
        diet = request.GET['diet']
        if diet:
            queryset_list = queryset_list.filter(diet__lte=diet)

    if 'difficulty' in request.GET:
        difficulty = request.GET['difficulty']
        if difficulty:
            queryset_list = queryset_list.filter(difficulty=difficulty)

    category_choices = {v.value: v.label for k, v in Recipe.CategoryChoices}
    diet_choices = {v.value: v.label for k, v in Recipe.DietChoices}
    difficulty_choices = {v.value: v.label for k, v in Recipe.DifficultyChoices}

    paginator = Paginator(queryset_list, 6)
    page = request.GET.get('page')

    try:
        page_recipes = paginator.page(page)
    except PageNotAnInteger:
        page_recipes = paginator.page(1)
    except EmptyPage:
        page_recipes = paginator.page(paginator.num_pages)

    context = {'category_choices': category_choices,
               'diet_choices': diet_choices,
               'difficulty_choices': difficulty_choices,
               'recipes': page_recipes,
               'values': request.GET
               }

    return render(request, 'recipes/search.html', context)

templates/recipes/create_recipe.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}
{% load ratings %}

{% block title %} | Stwórz przepis{% endblock %}


{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Stwórz swój własny przepis</h1>
                    <p class="lead">
                        I podziel się nim z innymi <i class="fas fa-utensils text-secondary"></i></p>
                </div>
            </div>
        </div>
    </section>

    <br>
    {% include 'partials/_alerts.html' %}


    <section id="register" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-10 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-center" id="showcase-form">
                            <div class="container">
                                <div class="row text-center">
                                    <div class="col-md-12">
                                        <h4 class="text-white">Twój przepis</h4>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">

                            {% include 'partials/_alerts.html' %}
                            <form action="{% url 'create_recipe' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}

                                {% for field in form %}
                                    <div class="form-group">
                                        {{ field.label_tag }} {{ field }}
                                        {% if field.help_text %}
                                            <p class="help">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                        {{ field.errors }}
                                    </div>

                                {% endfor %}

                            <button class="btn btn-secondary btn-block mt-4" type="submit">Opublikuj</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="py-5 bg-secondary text-white">
        <div class="container">
            <div class="row text-center justify-content-md-center">
                <div class="col-md-4">
                    <i class="fas fa-book-open fa-4x mr-4"></i>
                    <hr>
                    <h3>Zbieraj przepisy</h3>
                    <p>Zaznaczaj ulubione przepisy i stwórz swoją własną bazę najlepszych przepisów</p>
                </div>
                <div class="col-md-4">
                    <i class="far fa-star fa-4x mr-4"></i>
                    <hr>
                    <h3>Oceniaj przepisy</h3>
                    <p>Skorzystałeś z przepisu?<br>Daj znać czy było smacznie!</p>
                </div>
            </div>
        </div>

    </section>



{% endblock %}

templates/recipes/edit_recipe.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}
{% load ratings %}

{% block title %} | Stwórz przepis{% endblock %}


{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Edytuj swój przepis</h1>
                    <p class="lead">
                        Żeby bylo jeszcze smaczniej<i class="fas fa-utensils text-secondary"></i></p>
                </div>
            </div>
        </div>
    </section>

    <br>
    {% include 'partials/_alerts.html' %}


    <section id="register" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-10 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-center" id="showcase-form">
                            <div class="container">
                                <div class="row text-center">
                                    <div class="col-md-12">
                                        <h4 class="text-white">Twój przepis</h4>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">

                            {% include 'partials/_alerts.html' %}
                            <form action="{% url 'edit_recipe' recipe_id %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}

                                {% for field in form %}
                                    <div class="form-group">
                                        {{ field.label_tag }} {{ field }}
                                        {% if field.help_text %}
                                            <p class="help">{{ field.help_text|safe }}</p>
                                        {% endif %}
                                        {{ field.errors }}
                                    </div>

                                {% endfor %}
                                <button class="btn btn-secondary btn-block mt-4" type="submit">Zapisz zmiany</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="services" class="py-5 bg-secondary text-white">
        <div class="container">
            <div class="row text-center justify-content-md-center">
                <div class="col-md-4">
                    <i class="fas fa-book-open fa-4x mr-4"></i>
                    <hr>
                    <h3>Zbieraj przepisy</h3>
                    <p>Zaznaczaj ulubione przepisy i stwórz swoją własną bazę najlepszych przepisów</p>
                </div>
                <div class="col-md-4">
                    <i class="far fa-star fa-4x mr-4"></i>
                    <hr>
                    <h3>Oceniaj przepisy</h3>
                    <p>Skorzystałeś z przepisu?<br>Daj znać czy było smacznie!</p>
                </div>
            </div>
        </div>

    </section>

{% endblock %}

templates/recipes/recipe.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %}
{% load ratings %}

{% block title %} | {{ recipe.title }}{% endblock %}

{% block headscripts %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{% endblock %}


{% block content %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">{{ recipe.title }}</h1>
                    <p class="lead">
                        <i class="fas fa-utensils text-secondary"></i>
                        Kategoria: {{ recipe.get_category_display }}</p>
                </div>
            </div>
        </div>
    </section>

    <br>
    {% include 'partials/_alerts.html' %}


    <!-- Recipe -->
    <section id="recipe" class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- Main Image -->
                    <div class="row">
                        <div class="col-md-8 offset-md-2">
                            <img src="{{ recipe.photo_main.url }}" alt="główne zdjęcie" class="img-main img-fluid mb-3">
                            <!-- Thumbnails -->
                            <div class="row mb-5 thumbs">
                                {% if recipe.photo_main %}
                                    <div class="col-md-2">
                                        <a href="{{ recipe.photo_main.url }}" data-lightbox="meal-images">
                                            <img src="{{ recipe.photo_main.url }}" alt="" class="img-fluid">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if recipe.photo_1 %}
                                    <div class="col-md-2">
                                        <a href="{{ recipe.photo_1.url }}" data-lightbox="meal-images">
                                            <img src="{{ recipe.photo_1.url }}" alt="" class="img-fluid">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if recipe.photo_2 %}
                                    <div class="col-md-2">
                                        <a href="{{ recipe.photo_2.url }}" data-lightbox="meal-images">
                                            <img src="{{ recipe.photo_2.url }}" alt="" class="img-fluid">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if recipe.photo_3 %}
                                    <div class="col-md-2">
                                        <a href="{{ recipe.photo_3.url }}" data-lightbox="meal-images">
                                            <img src="{{ recipe.photo_3.url }}" alt="" class="img-fluid">
                                        </a>
                                    </div>
                                {% endif %}
                                {% if recipe.photo_4 %}
                                    <div class="col-md-2">
                                        <a href="{{ recipe.photo_4.url }}" data-lightbox="meal-images">
                                            <img src="{{ recipe.photo_4.url }}" alt="" class="img-fluid">
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>


                    <!-- Fields -->
                    <div class="row mb-5 fields">
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-sign-language"></i> Stopień trudności:
                                    <span class="float-right">{{ recipe.get_difficulty_display }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-user-plus"></i> Porcje:
                                    <span class="float-right">{{ recipe.serves }}</span>
                                </li>

                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-star"></i> Ocena użytkowników:
                                    <span class="float-right">{% ratings recipe %}</span>
                                </li>
                            </ul>

                        </div>
                        <div class="col-md-6">
                            <ul class="list-group list-group-flush">

                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-info"></i> Dieta:
                                    <span class="float-right">{{ recipe.get_diet_display }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-clock"></i> Czas przygotowania:
                                    <span class="float-right">{{ recipe.preparation_time_in_minutes }}minut</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-user"></i> Autor przepisu:
                                    <span class="float-right">{{ recipe.author }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <i class="fas fa-calendar-alt"></i> Data dodania:
                                    <span class="float-right">{{ recipe.added_date | date:'d N' }}</span>
                                </li>
                                <li class="list-group-item text-secondary">
                                    <!-- Buttons -->
                                    <button class="btn btn-primary"
                                            {% if is_favourite %}style="display:none;"{% endif %}
                                            id="add-to-favourites" value="{{ recipe.id }}">Dodaj do
                                        ulubionych
                                    </button>

                                    <button class="btn btn-primary"
                                            {% if not is_favourite %}style="display:none;"{% endif %}
                                            id="remove-from-favourites" value="{{ recipe.id }}">Usuń z ulubionych
                                    </button>

                                    {% if user == recipe.author %}
                                        <a href="{% url 'edit_recipe' recipe.id %}" class="btn btn-primary">Edytuj przepis</a>
                                    {% endif %}

                                    {% csrf_token %}
                                </li>
                            </ul>
                        </div>
                    </div>


                    <div class="row mb-5">
                        <!-- Ingredients-->
                        <div class="col-md-3">
                            <h3 class="text-secondary">Składniki:</h3>
                            {{ recipe.ingredients|linebreaks }}
                        </div>
                        <!-- Description -->
                        <div class="col-md-9">
                            <h3 class="text-secondary">Opis przygotowania:</h3>
                            {{ recipe.description|linebreaks }}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script>
        $(document).ready(function () {
            $("#add-to-favourites").click(function () {
                {% if user.is_authenticated %}
                    var recipe_id = $(this).val();
                    console.log(recipe_id)
                    var csrf_token = $('input[name="csrfmiddlewaretoken"]').val();
                    var addToFavourites = $.ajax({
                        "url": "{% url 'add_to_favourites' %}",
                        "type": "POST",
                        'data': {
                            'recipe_id': recipe_id,
                            'csrfmiddlewaretoken': csrf_token
                        },
                        'dataType': 'json',
                        success: function (response) {
                            console.log(response);
                            $("#add-to-favourites").hide();
                            $("#remove-from-favourites").show();
                        },
                        error: function (response) {
                            console.log(response["responseJSON"]["error"]);
                        }
                    });

                {% else %}
                    alert('Żeby dodać przepis do ulubionych musisz być zalogowany');
                {% endif %}
            })
        });

        $(document).ready(function () {
            $("#remove-from-favourites").click(function () {
                {% if user.is_authenticated %}
                    var recipe_id = $(this).val();
                    console.log(recipe_id)
                    var csrf_token = $('input[name="csrfmiddlewaretoken"]').val();
                    var removeFavourites = $.ajax({
                        "url": "{% url 'remove_from_favourites' %}",
                        "type": "POST",
                        'data': {
                            'recipe_id': recipe_id,
                            'csrfmiddlewaretoken': csrf_token
                        },
                        'dataType': 'json',
                        success: function (response) {
                            console.log(response);
                            $("#remove-from-favourites").hide();
                            $("#add-to-favourites").show();
                        },
                        error: function (response) {
                            console.log(response["responseJSON"]["error"]);
                        }
                    });

                {% else %}
                    alert('Żeby usunąć przepis z ulubionych musisz być zalogowany');
                {% endif %}
            })
        })
    </script>
{% endblock %}

templates/recipes/recipes.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %} | Przepisy{% endblock %}

{% block content %}

    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">Nasze przepisy</h1>
                    <p class="lead">Smacznego!</p>
                </div>
            </div>
        </div>
    </section>


    <!-- Recipes -->
    <section id="listings" class="py-4">
        <div class="container">
            <div class="row">

                {% if recipes %}
                    {% for recipe in recipes %}
                        {% include 'partials/_recipe.html' %}
                    {% endfor %}
                {% else %}
                    <div class="col-md-12">
                        <p>Nie ma jeszcze żadnych przepisów. Bądź pierwszy!</p>
                    </div>
                {% endif %}

            </div>

            <!-- Pagination -->
            <div class="row">
                <div class="col-md-12">
                    {% if recipes.has_other_pages %}
                        <ul class="pagination">
                            {% if recipes.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ recipes.previous_page_number }}" class="page-link">&laquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link">&laquo;</a>
                                </li>
                            {% endif %}

                            {% for i in recipes.paginator.page_range %}
                                {% if recipes.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if recipes.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ recipes.next_page_number }}" class="page-link">&raquo;</a>
                                </li>
                            {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link">&raquo;</a>
                                </li>
                            {% endif %}

                        </ul>
                    {% endif %}
                </div>
            </div>

        </div>
    </section>

{% endblock %}